name: Deploy to VM

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd ~/backend/sejonghack

            echo "Pulling latest code from develop branch"
            git pull origin develop

            echo "Building project without running tests"
            ./gradlew build -x test

            echo "Killing existing Java process (if any)"
            (pkill -f 'java -jar') || true

            echo "Starting new application process"
            nohup java -jar \
              -Dspring.datasource.url="jdbc:mysql://40.233.103.122:3306/sejongdb?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC" \
              -Dspring.datasource.username="jun" \
              -Dspring.datasource.password="CgD)@voN%_4~tDsiWPLhb" \
              build/libs/sejonghack-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
