name: Auto Deploy to VM

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd ~/backend/sejonghack
            git pull origin develop
            ./gradlew build
            pkill -f 'java -jar' || true
            nohup java -jar build/libs/sejonghack-0.0.1-SNAPSHOT.jar &
