name: Deploy to VM

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd ~/backend/sejonghack

            echo "git pull"
            git pull origin develop

            echo "build without tests"
            ./gradlew build -x test

            echo "kill previous java processes"
            pkill -f 'java -jar' || true

            echo "run new jar in background"
            DB_URL="jdbc:mysql://40.233.103.122:3306/sejongdb?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC" \
            DB_USER="jun" \
            DB_PASS="CgD)@voN%_4~tDsiWPLhb" \
            nohup java -jar build/libs/sejonghack-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 & disown
