name: Auto Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
            cd ~/backend/sejonghack
            git pull origin develop
            ./gradlew clean build
            sudo pkill -f 'java -jar'
            nohup java -jar ./build/libs/*.jar > app.log 2>&1 &
          EOF